### ISSUE TITLE
Occurrence skipping and one-offs

### ISSUE THREAD

**Issue by gpennington** [gregplaysguitar/django-eventtools#20]
Great tool.  Enjoying it, but for our use, it's needs one more feature.

The ability to make an Occurrence entry that can either a) override an occurrence or b) remove an occurrence.

So, the weekly Tuesday, 2:00pm meeting is at 3:00pm this week and cancelled next week.

**Comment by gregplaysguitar** [comment]
Ok, that sounds useful but definitely not trivial. I don't have any time just at the moment but if you're up for writing some code and making a PR I'll definitely help integrate it. Did you have an idea of what the model should look like?

**Comment by kevindice** [comment]
I need this too.  To not break backwards compatibility, how about a mixin-style treatment for this?  Users could opt to this functionality or continue to use the base classes in exactly the same way.

Thinking out loud a bit...

Currently, an Occurrence can either be a single occurrence or a pattern-based generator for a set of occurrences.  It's important to note that these generated occurrences don't actually exist, preventing any kind of DB foreignkey reference to them.  It might be necessary to make another table with a FK to the occurrence generator (an Occurrence with repetition) which is queried during the expansion of a single Occurrence to a queryset of them.  In this case, such a mixin would simply override that function.

I'm digging through the source now and will suggest a solution soon.

**Comment by kevindice** [comment]
Exceptions to [rrules](https://labix.org/python-dateutil#head-470fa22b2db72000d7abe698a5783a46b0731b57) is not a feature of the RFC or the python-dateutil implementation, so the collection of occurrences must be modified with all known exceptions **after** initial generation.

**Comment by gregplaysguitar** [comment]
Hi, yeah I think relating an exception to a specific occurrence is the main issue for me. The simplest way would seem to be to store a datetime on the exception and when it matches an occurrence, apply the exception. The model could look like

    class Exception(models.Model):
        occurrence = models.ForeignKey(Occurrence)
        start = models.DateTimeField()
        modified_start = models.DateTimeField(null=True)
        modified_end = models.DateTimeField(null=True)

This seems a bit brittle, and could easily be implemented with the existing code by overriding `BaseOccurrence.all_occurrences`, so I don't think it belongs in the codebase as is.

**Comment by isolationism** [comment]
> Exceptions to rrules is not a feature of (...) the python-dateutil implementation

I think you may be mistaken, @kevindice; Exceptions are present in `python-dateutil` but must be applied to `rruleset` objects and not `rrules` because each exception is itself a rule.

[rruleset methods](https://labix.org/python-dateutil#head-717a8f5a506d997f07db99aeb71b76ea991f9309) — see `exrule()` and `exdate()` methods, as well as the second example, which illustrates the usage of the `exdate()` method to remove a recurrence date.

**Comment by isolationism** [comment]
For anyone else encountering this issue and looking for a bit of help with a solution, here's a code snippet that may help:

```
from dateutil.rrule import rruleset
from eventtools.models import (BaseEvent, BaseOccurrence, default_naive)
from django.db import models

class MyEvent(BaseEvent):
   # My model properties here

class MyEventOccurrence(BaseOccurrence):
    # My model properties here
    event = models.ForeignKey(MyEvent)
    exclusions = models.ManyToManyField(to='MyEventOccurrenceExclusion')

    def get_repeater(self):
        rule = super().get_repeater()  # gets an rrule from parent method
        ruleset = rruleset()  # enables more sophisticated recurrence logic
        ruleset.rrule(rule)
        for exclusion in self.exclusions.all():
            ruleset.exdate(default_naive(exclusion.start))  # remove occurrence
            if exclusion.modified_start:  # reschedule occurrence if defined
                ruleset.rdate(default_naive(exclusion.modified_start))
        return ruleset

class MyEventOccurrenceExclusion(models.Model):
    start = models.DateTimeField()
    modified_start = models.DateTimeField(blank=True, null=True)    
```

Usage is straightforward; create one or more related `MyEventOccurrenceExclusion` objects with a `start` datetime that exactly matches the datetime of one of your event's occurrence. 

If you leave `modified_start` blank, it will merely cancel that occurrence. If you supply the optional `modified_start` datetime, it will reschedule the cancelled occurrence to the new datetime (albeit with the same event duration).

While I think the use of `rruleset` instead of `rrule` is such a straightforward addition that it could — and probably should — be added to the codebase, the brittleness @gregplaysguitar refers to is a bit more difficult to mitigate: The `MyEventOccurrenceExclusion.start` property must _exactly_ match the datetime of a calculated occurrence to work, otherwise it has no effect whatsoever on the output. 

One possible solution would be to validate that each related exclusion date match an occurrence when saving an event, but that's not particularly elegant, and means extra headaches for validation.

**Comment by gregplaysguitar** [comment]
Nice, thanks for this. Seems like it would be worthwhile switching to rruleset in the codebase for flexibility so let's do that. I think there should also be an example of how to implement exceptions in the docs, and your code looks like a good starting point for that.

**Comment by isolationism** [comment]
You're most welcome. I'm grateful for a chance to return a little of your generosity in writing and maintaining this package for us all.
