### ISSUE TITLE
Django 3 support

### ISSUE THREAD

**Issue by JorneVL** [gregplaysguitar/django-eventtools#32]
Hello,

There are some issue when upgrading to Django 3.0.
The first item where it fails is python_2_unicode_compatible.
Is it possible to release a new version with support for Django 3.0?
This lib is used in CoderedCMS and we need this for the upgrade, see https://github.com/coderedcorp/coderedcms/issues/290

Kind regards,
Jorne

**Comment by gregplaysguitar** [comment]
Hi, I'd definitely like to support Django 3, but I don't have a lot of time to put into this right now. If you were able to supply a patch that would be great. Otherwise I'll have a look as soon as I have time. I made a branch to update the versions the tests run against - see #33 - that should show the problems, but I haven't fixed any yet

**Comment by gregplaysguitar** [comment]
Actually... that might have been easier than expected. @JorneVL do you mind checking out the django-3 branch to confirm it all works for you? Assuming it does I'll do a release

**Comment by JorneVL** [comment]
Works fine, thank you.

**Comment by gregplaysguitar** [comment]
Cool, v1.0.0 is released which supports Django 3 🎉
