### ISSUE TITLE
Improve docs regarding Queryset filtering

### ISSUE THREAD

**Issue by edu2004eu** [gregplaysguitar/django-eventtools#43]
The section regarding queryset filtering specifies:

> Event and Occurrence querysets can be filtered, but due to uncertainty with repetitions, **from_date filtering is only an approximation** (whereas to_date filtering is accurate).

It would be nice to know what exactly this means. How is it an approximation or what results should we expect?

I'm currently afraid to use those functions, as I'm not sure how they will behave.

**Comment by gregplaysguitar** [comment]
Fair enough - the problem is that we can't tell for sure if a event will happen _after_ a certain date or not without evaluating repetition rules, meaning it can't be done as part of a database query. You can pass the `exact` option and it will filter for you using by evaluating the rules, you just need to be wary of excessive CPU usage

Is this better? https://github.com/gregplaysguitar/django-eventtools/pull/44

**Comment by edu2004eu** [comment]
@gregplaysguitar that looks great. Thanks!
